---
message: |
  --server - нужно ли сгенерировать шаблон для сервера
  --client - нужно ли сгенерировать шаблон для клиента
  --hygen - оставить ли шаблоны для дополнительной генерации сервера, root-а или клиента
  --product-id - уникальный идентификатор вашего продукта (в формате - PXXXX)
  --product - название команды разработки (pof, pdm, e.t.c)
  --channel-ids - идентификатор канала в loop для отсылки сообщений о сборке/деплое
  --namespace-prefix - Имя пространства имён в k8s (Пример - payment-pof)
  --service-account - Имя сервисного аккаунта для Jenkins (Пример - lm-sa-payment)
  --stage-clusters - Имена stage серверов k8s (Пример - sirius-a-stage, можно указывать через ',')
  --prod-clusters - Имена prod серверов k8s (Пример - payment,sirius-a, можно указывать через ',')
  --namespace - Имя пространства имён для Vault (Пример - payment)
  --approle-credentials-id - (Пример - approle-repository-factory)
  --project-name - имя продукта для Artifactory (Пример - payment)
  --service-name - имя продукта для Jenkins (Пример - my-new-shiny-app)
  --service-description - краткое описание продукта (как он будет отображаться во вкладке браузера) (Пример - 'My new shiny app RU')
  --credentials-id - Имя хранения секретов в среде Jenkins для доступа в Vault (Пример - ghe-svc-lmru-payment-jenkins-integration)
  --cut-examples - Удалять ли примеры использования функционала
  --add-web-socket - Добавить веб-сокет контроллеры
---
